version: "2"
services:

  mail:
    image: mailhog/mailhog
    restart: 'always'
    ports:
      - 1025:1025
      - 8025:8025
    links:
      - fpm
      - db   

  web:
    image: domw/magento2-nginx:1.17
    restart: 'always'
    ports:
      - 80:80
      - 443:443
    links:
      - fpm
      - db
      # - search
    volumes:
      - ./magento:/var/www/magento
    env_file:
      - ./global.env

  fpm:
    hostname: fpm.magento2.docker
    image: domw/magento2-php:7.2-fpm
    restart: 'always'
    ports:
      - 9000
    links:
      - db
      # - search
    volumes:
      - ./magento:/var/www/magento
    env_file:
      - ./global.env

  db:
    image: mariadb:10.4
    restart: 'always'
    ports:
      - 3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
      - TERM=meh

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: 'always'
    links: 
      - db:db
    ports:
      - 8000:80
    environment:
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
      - MYSQL_ROOT_PASSWORD=magento2       

  cli:
    hostname: cli.magento2.docker
    image: domw/magento2-php:7.2-cli
    links:
      - db
    volumes:
      - ./composer/cache:/root/.composer/cache
      - ./composer/auth.json:/root/.composer/auth.json
      - ./magento:/var/www/magento
      - ./mysql/conf:/etc/mysql/conf.d
    env_file:
      - ./global.env
      - ./composer.env
    environment:
      - M2SETUP_INSTALL_DB=true
      - M2SETUP_DB_HOST=db
      - M2SETUP_DB_NAME=magento2
      - M2SETUP_DB_USER=magento2
      - M2SETUP_DB_PASSWORD=magento2
      - M2SETUP_BASE_URL=http://magento2.docker/
      - M2SETUP_SECURE_BASE_URL=http://magento2.docker/
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=dominic@xigen.co.uk
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=test123
      - M2SETUP_VERSION=2.3.*
      - ENABLE_SENDMAIL=false
      # - M2SETUP_USE_SAMPLE_DATA=true

  cron:
    image: domw/magento2-php:7.2-cli
    hostname: magento2-cron.docker
    command: run-cron
    env_file:
      - ./global.env    
    environment:
      - ENABLE_SENDMAIL=false
    volumes:
      - ./magento:/var/www/magento
      - ./magento/var/log:/var/log/
    links:
      - db

  # search:
  #   image: elasticsearch:6.8.6
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - discovery.type=single-node
  #   volumes:
  #     - ./elasticsearchdata:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
